coq/coq.github.io

pages/1.html
This modification has been tested using the "make run" option described in README
=> corrects the fact that the pointer to Coq workshop get 'page not found'

pages/31.html
These new instructions take into account:
* the replacement of `:` by `-`;
* the recommendation to pin the version of Coq;
* the case of Coq beta.
=> Updated OPAM instructions

pages/104.html, pages/110.html, pages/3.html
Instructions to install Coq with OPAM on the download page.
=> Coq releases opam

PAGES, pages/131.html, pages/88.html
As organizer for Coq Workshop 2016 I would like to add the webpage on Coq's site as for previous years.
=> Add web page for the Coq Workshop 2016

pages/community.html, pages/faq.html, pages/index.html, pages/packages.html, styles/barron/style.css
@mattam82 please check the new text I wrote with @maximedenes 
The second commit is relevant for the PR on coq-opam-archive where the instruction on how to install a package or write a package use code blocks (the css is shared among the 2 sites)
=> community and contribution-index pages switched to OPAM

Makefile
By default, http.server binds to all interfaces (0.0.0.0). Unfortunately
there is no way to select the address to bind to for the
SimpleHTTPServer module from the command line in Python 2.7.
This is both safer (the testing server isn't potentially accessible to the
outside world) and avoids a security warning in OS X due to Python requesting
access to incoming network connections.
=> For python3, bind testing server only to localhost

news/130, news/131
The download links for 8.5pl2 and pl3 used the default download location, which I reported in Bugzilla as 5409. I've substituted the coq-85 download link.
=> use /coq-85 link instead of /download for 8.5pl2 and 8.5pl3

pages/community.html
Such a link was requested in https://coq.inria.fr/bugs/show_bug.cgi?id=4570.
=> add Github link to Community page

pages/coq-workshop/2018PL.html, pages/coq-workshop/index.html
This commit adds a line in the web-page of coq workshops and a page for the CoqPL workshop
that will take place in January.
Local tests were performed with success.
=> Adding a preliminary web-page for the CoqPL 2018 workshop.

pages/download.html
This was giving it more importance than is deserved.
The link to the tutorial still appears on the Documentation page.
(I was suggested this removal by Hugo.)
=> Remove Tutorial from Download page

pages/index.html
Main page on [Coq website](https://coq.inria.fr) contains an extraneous space.
=> Remove space from main page.

pages/community.html
These are the capitalization changes Hugo requested in https://coq.inria.fr/bugs/show_bug.cgi?id=4570, except for "bug tracking", which I don't think would look right. "Coqdev" is capitalized by analogy with "Coq-club", and "Working Group" has an official status, justifying a proper noun, while "bug tracking" is just a generic sort of thing.
=> Capitalize some words for uniformity

news/121
This news item contains a bad hyperlink, and is otherwise obsolete.
Pinging @maximedenes
=> Remove obsolete news item with bad link

incl/header.html, pages/about-coq.html, pages/index.html
This follows a suggestion by @Zimmi48.
=> Make download links point to download page instead of GitHub

pages/documentation.html
Do not mention PDF version of the refman since it doesn't exist anymore (closes coq/coq#7454).
Use direct links to Cocorico and the FAQ.
Remove prominent links to the Tutorial and the RecTutorial (but keep the in the full list).
I'll self-merge in a few days if no comments.
=> Update links to documentation.

pages/coq-workshop/index.html
This change was tested by typing
make
make run
and checking that the new links were valid.
=> adds 2018 Coq FLoC and 2019 CoqPL workshops in the list

pages/download.html, pages/opam-layout.html, pages/opam-packaging.html, pages/opam-using.html, pages/packages.html
I believe this information belongs to this repository rather than to the `opam-coq-archive` which gathers the data.
Also, having the source of the static part of the web site scattered across several repositories is less convenient (for maintenance, deployment, etc.).
=> Add OPAM documentation

pages/community.html, pages/coq-workshop/index.html, pages/coqpl.html, pages/index.html
What is missing: I'm intending to clearly separate the Coq workshops and CoqPL workshops and make sure that the list is exhaustive.
=> Advertise Discourse and rework community page.

pages/community.html, pages/other-events.html
In particular, mention the Math-Comp Winter School and the UniMath schools which were not listed there yet. Are there other recurring schools that I don't know about?
We could also mention non-recurring events, such as:
- http://www.strub.nu/coq-itp-15/
- http://www.cis.upenn.edu/~rrand/popl_2016/
- etc.
In any case, the goal of this PR, and the previous one (#92) is clearly to give more visibility to Coq events and to show to the public that we are a very active community, but also to encourage anyone organizing an event to open a PR and add it to the list.
=> Start listing Coq schools in the community page.

pages/opam-using.html
- Simplify installation instructions (follow up of discussion at #95 and #96)
- Clarify opam version requirement (fixes #101)
- Move information related to roots and switches to an "Advanced usage" section.
- Rename OPAM to opam. https://github.com/ocaml/opam/issues/2645
=> Update instructions to install via opam

Makefile
This was sometimes hiding problems (permissions, etc), and other
components (Coq Package Index) were reyling on the yamlpp executable to
be built.
=> Stop using yamlpp as a script

pages/opam-packaging.html
Follow up from post-merge comment in #119, and the URL thing is for consistency.
=> Opam packaging tutorial: Fix a command and simplify an URL

files/nahas_tutorial.v
This patch fixes the typo: two conjunction signs is used instead of a single conjunction and a single disjunction signs
=> Closes #134 - Typo in nahas_tutorial.v

pages/opam-using.html
I applied some suggestion from a recent Coq-Club user who had trouble following the opam instructions. I am submitting this for review though, because I am not myself an opam user.
Regarding the `m4` package, is it frequent that this is not installed by default?
@Lysxia or @palmskog or anyone else that is experienced with opam: would you mind reviewing this PR?
=> Apply feedback from Rajeev Gore on Coq-Club.

pages/index.html, pages/opam-using.html, pages/related-tools.html, pages/user-interfaces.html
- Try to list all significant user interfaces, including discontinued ones.
- Organize this page in three categories: support extensions, standalone interfaces, and experimental / discontinued interfaces.
- Remove the user interface section from the Related Tools page.
- Mention prominently the User interfaces page on the index page.
Fix #123.
=> Create a page dedicated to user interfaces. 

pages/opam-packaging.html
Isn't there a typo in this command line?
=> Typo in the page about creating coq opam packages

pages/opam-packaging.html
This prevents the user from forgeting a `url` field in their opam file.
=> Recommending `opam lint --check-upstream`

pages/community.html, pages/index.html
Screenshot:
@anton-trunov, @JasonGross and others: am I missing some active Coq places?
Maybe we should list Codewars somewhere on the community page but I'm not sure where it fits best.
=> Update to Zulip. List more communication channels.

Makefile
`coq-workshop/2009/cfp` and `news/69` don't appear to exist.
=> Makefile: Remove dead link to Coq Workshop 2009 CFP

incl/macros.html, pages/about-coq.html, pages/documentation.html, pages/download.html, pages/index.html, pages/opam-using.html
This is a major update to the website home page and Coq installation pages to put the focus on the Coq platform installation method (cc @gares @MSoegtropIMC). It also reduces the importance of the current version number on the website in relation with [CEP#52](https://github.com/coq/ceps/pull/52) (but we still need it, mostly in the opam using page). For the homepage, I also tried to think at what we would like to put forward if the design of the website was reworked, but without doing any change to the design yet.
The diff for the index page and the download page might be a bit hard to follow, so here are some preview screenshots:
cc @jfehrle (I cannot request a review from you on this repository)
=> Website simplification and Coq platform update.

incl/footer.html, incl/header.html, incl/news/title.html
The news section isn't used anymore except to announce new releases. We've recently acted that we wouldn't announce Coq releases anymore, only Coq platform releases. The last Coq platform release was announced on GitHub + Coq-Club + Discourse but not on the website for lack of time. Removing the news section would reduce the work of platform maintainers.
My proposal is a minimal change. I didn't remove the code that was able to generate the last three news items for the side-bar. I didn't remove the side-bar. I'm aware it is far from ideal but I'm also counting on a website redesign in (let's say) less than a year, and trying to focus on the content first.
Main page:
News page:
cc @herbelin who expressed the idea of linking to the pages that are actually used for announcements nowadays
cc …
=> Archive the news section.

pages/coq-team.html
@mattam82 As you proposed, I added a link to the opam bench. I did not add other links in this pull-request. How it appears with the link:
=> Add link to the opam-bench project in the Coq Team

aliases.footer.conf
After #176 was merged, I noticed that the redirect for `related-tools` was not working - it goes to the 404 URL: https://github.com/coq-community/awesome-coq%23tools
The problem is that the hashtag `#` is getting mangled/escaped. Per the [manual for RewriteRule](https://httpd.apache.org/docs/current/rewrite/flags.html#flag_ne), the correct way to fix this is using the option `NE` (NoEscape), which I do in this fix.
=> fix related-tools redirect mangling of hashtag

pages/documentation.html
The list of "books and long tutorials" has some outdated and missing links and is non-uniform, which I try to address in this PR.
Recently, a draft of a new 350+ page book on Coq appeared (https://github.com/uds-psl/MPCTT), but we should probably check with the author if he wants it listed before adding it, so I didn't include it here.
=> link updates and uniformization of book list

yamlpp-0.3/yamlpp.ml, yamlpp-0.3/yamlpp.mll
I removed a deprecated namespace in yamlpp.mll and the newly generated yamlpp.ml no longer emits a warning.
=> remove deprecation

pages/download.html, pages/index.html
Following a point made by Pierre Rousselin on the private mailing list gt-maths-coq, this PR makes two small modifications to the website to make it clearer how to get Coq.
1. Do not mention the "Platform" on the homepage because prospective users do not know yet what it is and there is no space to explain.
2. On the download page, clarify what is the recommended installation method for beginners, including for those who do not want to read the page closely.
3. This is outside the scope of this PR: the third change should be in the formatting of the Coq Platform releases (cc @MSoegtropIMC). We should insert three prominent links at the top of the GitHub releases pointing to the Windows (64 bit) installer, the macOS installer, and the Snap package. Something like:
```markdown
- [Windows …
```
=> Make it easier to get Coq.

incl/footer.html, pages/download.html, pages/opam-using.html
Note that Coq as a "platform" is sometimes used in a more general sense, so we'd like to avoid confusion. Also, consistently link to latest Platform release for the scripts.
=> consistently capitalize Platform when referring to Coq Platform

pages/community.html
A remnant from when the Windows installer was the main curated distribution.
=> mention about Coq Platform over installers in general context

pages/coq-team.html
One bug was left unfixed. The explicit doctype `<!DOCTYPE html>` at the top of the page causes browsers to choke on the implicit doctype coming from `incl/header.html`.
=> Upgrade Pierre Roux and fix various bugs in the team page

incl/macros.html
To be merged when `coqide.8.17.1` appears on opam.
cc: @Zimmi48
=> update CURRENTVERSION to 8.17.1

pages/community.html, pages/index.html
The Coq Community Survey 2022 reveal that a large part of the community (especially newcomers) was not aware of the code of conduct, and an even larger part had not read it. This is an attempt at improving the situation by advertising the Code of Conduct more broadly, through the Coq website, since it applies beyond the boundaries of the Coq repositories. This also follows the recent addition of a section specifically dedicated to asking questions on Coq forums in the code of conduct.
cc @coq/code-of-conduct-team
=> Advertise Code of Conduct on website.

pages/user-interfaces.html
The info was outdated. This is a minimal fix.
=> Update description of VSCode extensions

pages/user-interfaces.html
@herbelin As an alternative to #218, here are a few commits which implement the most needed changes to Coq's UI page without making any radical change (in particular to the structure).
Mostly, we:
- remove excessive information that cluttered the page
- move coq_jupyter to the top of the experimental section (since it doesn't really fit the "actively used" category)
- mention the existence of experimental NeoVim support for VsCoq and coq-lsp (although we might want to remove this mention if this experimental support stops being actively maintained in the future; for now, both linked projects are actively maintained by the same person).
I'm happy to drop any commit to make the merging of this PR quick and without debate. (Each commit can be considered independent.) I have no will to spend …
=> Most needed changes to Coq's UI page.

incl/macros.html
CC @Zimmi48:
- switch the default version of the reference manual on the website.
- publish a new manual version on Zenodo.
=> bump coq version to 8.18.0

pages/404.html, srv/server.py
When redirecting requests for stdlib or refman pages, propagate the
URL's fragment identifer (the string following the '#' sign, if any).
This is required for stdlib URLs so that links generated by coqdoc
resolve to specifc identifiers, as intended.
While at it, also preserve the fragment identifier in refman pages, in
case someone, somewhere meant to link to specific parts of the
reference manual.
Fixes: https://github.com/coq/coq.github.io/issues/235
Aside: tweaked `srv/server.py` to be able to test the 404 page locally.
=> propagate hash fragment (=href anchor) when redirecting URLs 

pages/coq-team.html
As was discussed at a previous Coq Call, we are now a team of coordinators with @ybertot, @tabareau and @Zimmi48.  @maximedenes , I moved you to the alumni, what should I put as your new affiliation/position at Inria?
=> Update the core and coordinators teams

incl/footer.html, incl/header.html
The Coq team announced a rename months ago, but there is no sign of it on the webpage. This is silly!
The present PR adds just a couple mentions of the new Rocq name, enough for people to know that this is happening for real -- but not enough that it is a lot of work or that tricky questions have to be answered for consistency.
The proposed explanation includes an invitation to use the combined name "Coq/Rocq" during a transition period, so that people that only know of the old name (that is, almost everyone) does not get lost. This is used on the webpage itself, whose title is now "The Coq/Rocq proof assistant."
=> mention the Rocq rename
