coq/coq.github.io

- NEWS
- news/125
- pages/110.html
Also mention the CHANGES file earlier.
> Update NEWS file for beta 2 and make it appear in recent news.

- pages/110.html
This reverts commit 06d8501cb2452ca4ebaa939c5a203a4f6157122a.
> Revert "DMG is broken..."

- pages/31.html
Because Google is still proposing this page.
> OPAM instructions commented out

- .gitignore
- README.md
- pages/31.html
- styles/barron/style.css
Missing: the documentation for the distribution mechanism.
> OPAM documentation

- pages/community.html
Following the recommendation of @bcpierce00 to strengthen the advice to hang out there, answer and ask questions.
> Mention StackOverflow / Stack Exchange.

- Makefile
- NEWSINDEX
- news/140
It took me a bit long to write this, but here it goes. Any comments @letouzey @maximedenes?
I'll merge this later this afternoon.
> News on migration to GitHub.

- pages/tutorial/0-getting-started.html
- pages/tutorial/1-basic-predicate-calculus.html
- pages/tutorial/2-induction.html
- pages/tutorial/3-modules.html
- pages/tutorial/index.html
This closes #52.
It was very weird copying code from a single HTML output file into a set of separate pages (containing macros).
I did this the best I could but I noticed at least two differences in the result (that make the diff hard to read): the use of `style` instead of pre-defined classes; and the overall indentation / line-break structure which is not as good in the compilation output than in the pages I'm changing. Is there a script to run to get the `class` and the indentation?
> Update tutorial following coq/coq#842.

- files/nahas_tutorial.v
- pages/tutorial-nahas.html
I edited the HTML produced by coqdoc to match the header/footer of existing file.
Modified the HTML produced by coqdoc to make links work.
I was unable to test this branch locally.
I ran "make" and "make run".   
Browser correctly loaded homepage at 127.0.0.1:8000
But, when I clicked on "documentation", I got 404 file-not-found error.
Same 404 error happens if I try to directly navigate to 127.0.0.1:8000/tutorial-nahas.
I opened dest/tutorial-nahas.html directly in a browser.
It rendered, with header and footer.
It did not have traditional coqdoc colors, like current version on the website.
(This may be because it could not find the CSS file.)
> Updated version of nahas tutorial.

- pages/documentation.html
cc @palmskog: I'd like to add a mention of FRAP and PnP, can you help provide descriptions?
cc @ejgallego: This might be related to your effort in coq/coq#9824.
cc tutorial authors @casteran @ybertot @bcpierce00 @andrew-appel @achlipala @amahboubi @gares: you might be interested or have comments, sorry for the noise if that's not the case.
This is the result:
> Rework documentation page, create more categories, mention MCB and dev doc.

- pages/coqpl.html
> Add CoqPL'20 to CoqPL page

- pages/opam-packaging.html
- styles/barron/style.css
> Update instructions to create packages for Opam 2.0

- Makefile
- pages/opam/www/index.html
- scripts/filter.js
- scripts/packages.js
- srv/server.py
- styles/package-index.css
> Read package data from JSON

- NEWSINDEX
- incl/macros.html
- news/coq-8-10beta3-is-out
- pages/index.html
> Announce Coq 8.10+β3

- pages/related-tools.html
Related tools now has a new section about tools for manipulating Coq developments.
> Add JasonGross/coq-scripts, JasonGross/coq-tools

- NEWSINDEX
- incl/macros.html
- news/coq-8-10-0-is-out
*Do not merge before the release actually happen.*
> Prepare announcement of Coq 8.10.0

- NEWSINDEX
- incl/macros.html
- news/coq-8-11beta1-is-out
> Prepare announcement of Coq 8.11+beta1.

- NEWSINDEX
- incl/macros.html
- news/coq-8-11-0-is-out
> Publish the 8.11.0 release.

- pages/download.html
Closes #144.
Preview:
@andres-erbsen Does this look good to you?
> Improve download page.

- NEWSINDEX
- incl/macros.html
- news/coq-8-12beta1-is-out
@ejgallego This announcement includes a call for help to improve the documentation on which we've been working with @jfehrle.
> Announce Coq 8.12+beta1.

- pages/consortium.html
We try to reflect better the current situation, in particular the various options for partners.
> Update Consortium page

- pages/consortium.html
@ybertot does this look good to you?
> Open support services to non-academic partners

- NEWSINDEX
- incl/macros.html
- news/coq-8-12-1-is-out
I'm currently in the process of uploading the Windows packages to GitHub. I'll merge this PR after I publish the release.
> Announce Coq 8.12.1.

- aliases.footer.conf
> Add a redirection to have a nix-shell for mathcomp

- aliases.footer.conf
> Redirection for coq-nix-toolbox

- pages/community.html
Update the website accordingly
> #coq moved from Freenode to Libera.Chat

- pages/coq-team.html
- styles/barron/style.css
This should be inherited from the base style.
Fixes #174
> Remove normal weights for links

- incl/macros.html
- pages/opam-using.html
hopefully addresses #175
fixes #175
I don't currently have a way of checking that this is really how it works, I am writing the doc from memory. Perhaps someone who has installed coq a few times recently can chip in.
cc @MSoegtropIMC
> update opam-using.html since opam-depext is no longer used

- pages/documentation.html
> add Hydras & Co. book to documentation

- incl/footer.html
- pages/index.html
> Advertise survey on website.

- pages/opam-using.html
https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Ocaml.20recommended.20version
> update ocaml version for opam

- pages/coq-team.html
> Add entries for Kenji Maillard and Ana Borges

- pages/documentation.html
In personal communication, the author gave permission to list the book on the page.
> list MPCTT book by Gert Smolka in documentation

- pages/user-interfaces.html
We also fix VsCode -> Visual Studio Code (or in any case VSCode)
Fixes https://github.com/ejgallego/coq-lsp/issues/156
> [interfaces] Add coq-lsp to interfaces

- pages/user-interfaces.html
It never reached the release state.
> Removed the reference tp PG async.

- LICENSE.md
As decided during today's Coq Call.
> Add CC-0 licensing to the Coq website.
